# Generated by Django 3.1.5 on 2021-03-18 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracks.custom_models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('artiste', models.CharField(max_length=50)),
                ('lyric', models.TextField(blank=True, null=True, verbose_name='Lyrics')),
                ('genre', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1024)),
                ('song_cover', models.ImageField(upload_to='song_covers/')),
                ('audio_file', tracks.custom_models.AudioFileField(upload_to='tracks/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('passtrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('album_cover', models.ImageField(upload_to='album_cover/')),
                ('artiste', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('track_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracks.track')),
                ('owner_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.album')),
            ],
            bases=('tracks.track',),
        ),
    ]
