# Generated by Django 3.1.7 on 2021-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='lyric',
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
