# Generated by Django 3.1.5 on 2021-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='Agree to terms and Condition'),
        ),
    ]
