# Generated by Django 3.1.7 on 2021-03-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0002_auto_20210322_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=144)),
                ('slug', models.SlugField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.track')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
        migrations.CreateModel(
            name='Refrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
        migrations.CreateModel(
            name='Chorus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lyric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
    ]
